# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_job_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='internal_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('ESTAGIO', 'Estagio'), ('EMPREGO', 'Emprego'), ('FREELANCER', 'FREELANCER')], default='ESTAGIO', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='open_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 13, 50, 49, 270348, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='workload',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2),
            preserve_default=False,
        ),
    ]
